# Generated by Django 4.1.4 on 2023-11-09 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Klient",
            fields=[
                ("id_klienta", models.AutoField(primary_key=True, serialize=False)),
                ("imie", models.CharField(max_length=50)),
                ("nazwisko", models.CharField(max_length=50)),
                ("wiek", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Oddzial",
            fields=[
                ("id_oddzialu", models.AutoField(primary_key=True, serialize=False)),
                ("lokalizacja", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Samochod",
            fields=[
                (
                    "numer_rejestracyjny",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("typ", models.CharField(max_length=50)),
                ("producent", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("cena", models.IntegerField()),
                ("skrzynia_biegow", models.CharField(max_length=50)),
                ("naped", models.CharField(max_length=50)),
                ("rok_dodania", models.IntegerField()),
                ("stan", models.CharField(max_length=50)),
                (
                    "id_oddzialu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.oddzial"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wypozyczenie",
            fields=[
                (
                    "id_wypozyczenia",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("data_wynajecia", models.DateField()),
                ("data_zwrotu", models.DateField()),
                (
                    "id_klienta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.klient"
                    ),
                ),
                (
                    "id_oddzialu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.oddzial"
                    ),
                ),
                (
                    "numer_rejestracyjny",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.samochod"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pracownik",
            fields=[
                ("id_pracownika", models.AutoField(primary_key=True, serialize=False)),
                ("imie", models.CharField(max_length=50)),
                ("nazwisko", models.CharField(max_length=50)),
                ("wiek", models.IntegerField()),
                ("staz_pracy", models.IntegerField()),
                (
                    "id_oddzialu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.oddzial"
                    ),
                ),
            ],
        ),
    ]